# Generated by Django 4.2.11 on 2024-04-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathtaggroup',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PathTag',
        ),
        migrations.DeleteModel(
            name='PathTagGroup',
        ),
    ]
