# Generated by Django 4.2.11 on 2024-04-21 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('file_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('bytesize', models.IntegerField()),
                ('filepath', models.TextField(blank=True, null=True)),
                ('filetype', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('done', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
