# Generated by Django 4.2.11 on 2024-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileunit',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
