# Generated by Django 4.2.11 on 2024-04-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_fileunit_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileunit',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileunit',
            name='store_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileunit',
            name='verification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
