# Generated by Django 4.2.11 on 2024-04-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_fileunit_published_fileunit_store_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileunit',
            name='deletion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
