# Generated by Django 4.2.11 on 2024-04-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_fileunit_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileunit',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
