# Generated by Django 4.2.11 on 2024-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='max_file_size',
            field=models.IntegerField(default=1, help_text='Gigabyte Units'),
        ),
    ]
