# Generated by Django 4.2.11 on 2024-04-27 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_fileinfocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_access', models.BooleanField(default=False)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='file.fileunit')),
            ],
        ),
    ]
