# Generated by Django 4.2.11 on 2024-04-28 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_filepermissionset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_processed', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='file.fileunit')),
            ],
        ),
    ]
