# Generated by Django 4.2.11 on 2024-04-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_fileprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(blank=True, max_length=255, null=True)),
                ('reader_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
