# Generated by Django 4.2.11 on 2024-05-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathaccess',
            name='reaccess_count',
            field=models.IntegerField(default=0),
        ),
    ]
