# Generated by Django 4.2.11 on 2024-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathtaggroup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
