# Generated by Django 4.2.11 on 2024-03-09 03:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinderblockPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(max_length=255)),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('polyclasses', wagtail.blocks.TextBlock(default='default', group='secondary', required=False)), ('content', wagtail.blocks.TextBlock())])), ('paragraph', wagtail.blocks.StructBlock([('polyclasses', wagtail.blocks.TextBlock(default='default', group='secondary', required=False)), ('content', wagtail.blocks.RichTextBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
